version: '3.3'

services:
  haproxy:
    image: haproxy-snapp:latest
    build: .
    container_name: haproxy
    restart: unless-stopped
    sysctls:
        - net.ipv4.ip_unprivileged_port_start=0   
    ports:
      - 80:80
      - 8404:8404
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    logging:
        driver: "json-file"
        options:
            max-size: "50m" 
    networks:
        snapp:
          ipv4_address: 10.0.1.10


  hello-snappmarket:
      image: hello-snappmarket:latest
      container_name: hello-snappmarket
      restart: unless-stopped       
      volumes:
          - /etc/localtime:/etc/localtime:ro
      networks:
        snapp:
          ipv4_address: 10.0.1.1


  timestamp1:
      image: timestamp:latest
      container_name: timestamp1
      restart: unless-stopped       
      volumes:
          - /etc/localtime:/etc/localtime:ro
      networks:
        snapp:
          ipv4_address: 10.0.1.2


  timestamp2:
      image: timestamp:latest
      container_name: timestamp2
      restart: unless-stopped       
      volumes:
          - /etc/localtime:/etc/localtime:ro
      networks:
        snapp:
          ipv4_address: 10.0.1.3



networks:
  snapp:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/16
         gateway: 10.0.1.0    